//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experteam
{
    using System;
    using System.Collections.Generic;
    
    public partial class guia_factura
    {
        public long id_guia_factura { get; set; }
        public int idguia { get; set; }
        public int idpago { get; set; }
        public Nullable<int> idfactura { get; set; }
    
        public virtual factura factura { get; set; }
    }
}
